name: probe
on:
  push:
  pull_request:
  pull_request_target:
  issues:
  issue_comment:
  watch:
  fork:
  create:
  release:
  workflow_run:
  repository_dispatch:
  check_suite:
  status:
  public:
  deployment:
  deployment_status:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: echo "EVENT=${{ github.event_name }} ACTOR=${{ github.actor }} SHA=${{ github.sha }}"
